project:
  type: book
  output-dir: docs

book:
  title: "Dialogues in Real Analysis"
  author: "Renu Dhadwal"
  chapters:
    - index.qmd
    - chapters/level1_completeness.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    html-math-method: mathjax
    css: course.css
    theorem: true

theorems:
  definition:
    name: Definition
    style: definition
  theorem:
    name: Theorem
    style: theorem
  example:
    name: Example
    style: example
  remark:
    name: Remark
    style: remark
